//
// Created by Hello Peter on 2021/11/11.
//

#ifndef TESTLINUX_SERVICEREGISTERDISCOVERY_H
#define TESTLINUX_SERVICEREGISTERDISCOVERY_H
class ServiceRegisterDiscovery
#endif //TESTLINUX_SERVICEREGISTERDISCOVERY_H
